export const styles: Record<string, React.CSSProperties> = {
  app: { maxWidth: '100%', minHeight: '100vh', display: 'flex', flexDirection: 'column', fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', Roboto, sans-serif" },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 20px', borderBottom: '1px solid #3d332e', background: '#241f1b', position: 'sticky', top: 0, zIndex: 100, backdropFilter: 'blur(8px)', gap: '12px' },
  headerLeft: { display: 'flex', alignItems: 'center', gap: '14px' },
  menuBtn: { background: 'none', border: 'none', cursor: 'pointer', padding: '4px', display: 'flex', alignItems: 'center' },
  brand: { fontFamily: "'Libre Bodoni', Georgia, serif", fontSize: '22px', fontWeight: 600, color: '#ebcfbc', letterSpacing: '0.5px', fontStyle: 'italic' },
  headerRight: { display: 'flex', alignItems: 'center', gap: '10px' },
  btnNotifications: { background: 'none', border: 'none', cursor: 'pointer', padding: '6px', position: 'relative', display: 'flex', alignItems: 'center' },
  notificationDot: { width: '10px', height: '10px', borderRadius: '50%', background: '#8f7666', transition: 'background 0.2s' },
  notificationDotUnread: { background: '#f5a623', boxShadow: '0 0 8px rgba(245,166,35,0.5)' },
  notificationBadge: { position: 'absolute', top: '-2px', right: '-4px', background: '#4caf50', color: '#fff', fontSize: '9px', fontWeight: 700, minWidth: '16px', height: '16px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '0 4px', border: '2px solid #241f1b' },
  btnDump: { background: '#c87800', color: '#fff', border: 'none', padding: '9px 18px', borderRadius: '2px', fontSize: '13px', fontWeight: 500, letterSpacing: '0.5px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' },
  searchFilterBar: { display: 'flex', alignItems: 'center', gap: '8px', padding: '12px 20px', borderBottom: '1px solid #3d332e', background: '#241f1b', position: 'sticky', top: '60px', zIndex: 99, backdropFilter: 'blur(8px)' },
  btnFilter: { background: '#2a211e', border: '1px solid #3d332e', color: '#8f7666', padding: '7px 12px', borderRadius: '2px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', fontFamily: "'VT323', monospace", fontSize: '14px', letterSpacing: '1px' },
  btnFilterActive: { borderColor: '#c87800', color: '#f5a623', background: 'rgba(200,120,0,0.1)' },
  searchInput: { flex: 1, background: '#2a211e', border: '1px solid #3d332e', color: '#ebcfbc', padding: '7px 12px', borderRadius: '2px', fontFamily: "'VT323', monospace", fontSize: '14px', letterSpacing: '1px', outline: 'none' },
  wall: { flex: 1, padding: '24px 16px', display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px', justifyItems: 'center', alignItems: 'start', overflowY: 'auto', height: 'calc(100vh - 130px)' },
  noteCard: { border: '2px solid rgba(61,51,46,0.4)', borderRadius: '2px', padding: '20px', width: '100%', maxWidth: '320px', cursor: 'pointer', transition: 'border-color 0.2s, box-shadow 0.2s', position: 'relative', boxShadow: '2px 4px 0 rgba(0,0,0,0.3)', maxHeight: '320px', overflow: 'hidden' },
  pin: { position: 'absolute', top: '-6px', left: '50%', transform: 'translateX(-50%)', width: '12px', height: '12px', borderRadius: '50%', background: '#c87800', boxShadow: '0 0 6px rgba(200,120,0,0.5)', zIndex: 2 },
  noteContent: { fontSize: '1.15rem', lineHeight: 1.5, marginBottom: '12px', overflow: 'hidden', paddingTop: '4px', position: 'relative', maxHeight: '140px', fontWeight: 500 },
  tags: { display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '12px' },
  tag: { fontFamily: "'VT323', monospace", fontSize: '13px', background: 'rgba(0,0,0,0.08)', padding: '2px 8px', borderRadius: '2px', letterSpacing: '1px' },
  footer: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingTop: '10px', borderTop: '1px solid rgba(0,0,0,0.1)', gap: '8px' },
  author: { display: 'flex', alignItems: 'center', gap: '8px', minWidth: 0, flexShrink: 1, overflow: 'hidden' },
  avatar: { width: '24px', height: '24px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: 700, fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif", flexShrink: 0, overflow: 'hidden' },
  avatarImg: { width: '100%', height: '100%', objectFit: 'cover' },
  authorName: { fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif", fontSize: '12px', fontWeight: 500, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: '100px', display: 'block', opacity: 0.8 },
  meta: { display: 'flex', alignItems: 'center', gap: '8px', fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif", fontSize: '11px', flexShrink: 0, fontWeight: 400, opacity: 0.8 },
  metaStat: { display: 'flex', alignItems: 'center', gap: '3px' },
  emptyState: { textAlign: 'center', padding: '60px 20px', color: '#8f7666', gridColumn: '1 / -1', fontFamily: "'JetBrains Mono', monospace", fontWeight: 400 },
  emptyStateBtn: { background: 'none', border: '1px solid #3d332e', color: '#c87800', padding: '6px 14px', borderRadius: '2px', cursor: 'pointer', fontFamily: "'JetBrains Mono', monospace", fontSize: '12px', fontWeight: 500, marginTop: '10px', letterSpacing: '1px' },
  loadingOverlay: { display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '40px', gridColumn: '1 / -1' },
  loadingSpinner: { width: '32px', height: '32px', border: '3px solid #3d332e', borderTopColor: '#c87800', borderRadius: '50%', animation: 'spin 0.8s linear infinite' },
  sideMenuOverlay: { position: 'fixed', inset: 0, zIndex: 300, background: 'rgba(26,22,20,0.7)', backdropFilter: 'blur(2px)', display: 'flex', alignItems: 'stretch', justifyContent: 'flex-start' },
  sideMenu: { width: '260px', background: '#241f1b', borderRight: '1px solid #3d332e', padding: '20px', display: 'flex', flexDirection: 'column', gap: '8px' },
  sideMenuTitle: { fontFamily: "'Libre Bodoni', Georgia, serif", fontSize: '18px', fontStyle: 'italic', color: '#ebcfbc', marginBottom: '12px', paddingBottom: '12px', borderBottom: '1px solid #3d332e' },
  sideMenuBtn: { background: 'none', border: 'none', color: '#8f7666', fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif", fontSize: '14px', fontWeight: 500, padding: '10px 12px', textAlign: 'left', cursor: 'pointer', borderRadius: '2px', transition: 'all 0.2s', letterSpacing: '0.3px', display: 'flex', alignItems: 'center', gap: '10px' },
  closeMenu: { marginTop: 'auto', color: '#8f7666', fontSize: '12px', textAlign: 'center', padding: '10px', cursor: 'pointer', fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif" },
  toast: { position: 'fixed', bottom: '24px', left: '50%', transform: 'translateX(-50%)', zIndex: 400, background: '#241f1b', border: '1px solid #f5a623', borderRadius: '2px', padding: '14px 20px', display: 'flex', alignItems: 'center', gap: '16px', boxShadow: '0 8px 24px rgba(0,0,0,0.5)' },
  toastText: { fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif", fontSize: '13px', fontWeight: 500, color: '#ebcfbc' },
  toastArrow: { background: '#c87800', color: '#fff', border: 'none', width: '32px', height: '32px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  toastTimer: { position: 'absolute', bottom: 0, left: 0, height: '2px', background: '#f5a623', width: '100%' },
  overlayScreen: { position: 'fixed', inset: 0, zIndex: 250, background: '#1a1614', display: 'flex', flexDirection: 'column' },
  overlayHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 20px', borderBottom: '1px solid #3d332e', background: '#241f1b', flexShrink: 0 },
  overlayTitle: { fontFamily: "'Libre Bodoni', Georgia, serif", fontSize: '18px', fontStyle: 'italic', color: '#ebcfbc' },
  overlayBody: { flex: 1, overflowY: 'auto', padding: '24px 20px' },
  overlayBtn: { background: 'none', border: 'none', color: '#8f7666', cursor: 'pointer', fontFamily: "'JetBrains Mono', monospace", fontSize: '13px', fontWeight: 500, letterSpacing: '0.5px' },
  overlayBtnAccent: { color: '#f5a623', fontWeight: 600 },
  input: { width: '100%', background: '#2a211e', border: '1px solid #3d332e', color: '#ebcfbc', padding: '12px 14px', borderRadius: '2px', fontSize: '14px', outline: 'none', marginBottom: '12px' },
  btnPrimary: { width: '100%', background: '#c87800', color: '#fff', border: 'none', padding: '12px', borderRadius: '2px', cursor: 'pointer', fontSize: '14px', fontWeight: 500, letterSpacing: '0.5px', marginTop: '8px' },
  btnDanger: { width: '100%', background: 'none', border: '1px solid #e94560', color: '#e94560', padding: '12px', borderRadius: '2px', cursor: 'pointer', fontSize: '13px', fontWeight: 500, marginTop: '12px' },
  btnSecondary: { width: '100%', background: '#2a211e', border: '1px solid #3d332e', color: '#8f7666', padding: '12px', borderRadius: '2px', cursor: 'pointer', fontSize: '13px', fontWeight: 500, marginTop: '8px' },
  authCard: { width: '100%', maxWidth: '380px', background: '#241f1b', border: '1px solid #3d332e', borderRadius: '4px', padding: '32px 24px', margin: 'auto' },
  authTitle: { fontFamily: "'Libre Bodoni', Georgia, serif", fontSize: '24px', fontStyle: 'italic', color: '#ebcfbc', textAlign: 'center', marginBottom: '8px' },
  authSubtitle: { textAlign: 'center', color: '#8f7666', fontSize: '13px', marginBottom: '24px' },
  authLink: { textAlign: 'center', marginTop: '16px', color: '#8f7666', fontSize: '13px' },
  authLinkBtn: { background: 'none', border: 'none', color: '#f5a623', cursor: 'pointer', fontSize: '13px', fontWeight: 500 },
  composeTextarea: { width: '100%', background: '#2a211e', border: '1px solid #3d332e', color: '#ebcfbc', padding: '14px', borderRadius: '2px', fontSize: '1.15rem', lineHeight: 1.6, resize: 'vertical', minHeight: '200px', outline: 'none', fontWeight: 500 },
  moodBtn: { background: '#2a211e', border: '1px solid #3d332e', color: '#8f7666', padding: '6px 12px', borderRadius: '2px', cursor: 'pointer', fontSize: '12px', fontWeight: 500, letterSpacing: '0.5px' },
  moodBtnSelected: { borderColor: '#c87800', color: '#f5a623', background: 'rgba(200,120,0,0.1)' },
  fontBtn: { background: '#2a211e', border: '1px solid #3d332e', borderRadius: '2px', padding: '10px 14px', cursor: 'pointer', textAlign: 'left', minWidth: '140px', flex: 1 },
  fontBtnSelected: { borderColor: '#c87800', background: 'rgba(200,120,0,0.1)' },
  noteDisplayFull: { padding: '24px', borderRadius: '2px', marginBottom: '24px', position: 'relative', border: '2px solid rgba(61,51,46,0.4)', lineHeight: 1.6, fontSize: '1.25rem', boxShadow: '2px 4px 0 rgba(0,0,0,0.3)', fontWeight: 500 },
  infoBlock: { background: '#2a211e', border: '1px solid #3d332e', borderRadius: '2px', padding: '14px', display: 'flex', flexDirection: 'column', gap: '4px' },
  infoLabel: { fontFamily: "'JetBrains Mono', monospace", fontSize: '9px', fontWeight: 500, color: '#8f7666', textTransform: 'uppercase', letterSpacing: '1.5px' },
  infoValue: { fontFamily: "'JetBrains Mono', monospace", fontSize: '14px', fontWeight: 400, color: '#ebcfbc' },
  comment: { background: '#2a211e', border: '1px solid #3d332e', borderRadius: '2px', padding: '14px', marginBottom: '10px' },
  commentAuthor: { fontFamily: "'JetBrains Mono', monospace", fontSize: '13px', fontWeight: 500, color: '#c49b7d', display: 'flex', alignItems: 'center', gap: '8px' },
  commentText: { color: '#8f7666', fontSize: '0.9rem', lineHeight: 1.7, fontFamily: "'JetBrains Mono', monospace", fontWeight: 300, fontStyle: 'italic' },
  commentTime: { fontSize: '10px', color: '#5f4a3c', marginTop: '6px', fontFamily: "'JetBrains Mono', monospace" },
  filterChip: { background: '#2a211e', border: '1px solid #3d332e', color: '#8f7666', padding: '7px 14px', borderRadius: '2px', cursor: 'pointer', fontSize: '13px', fontWeight: 500, whiteSpace: 'nowrap' },
  filterChipActive: { borderColor: '#c87800', color: '#f5a623', background: 'rgba(200,120,0,0.1)' },
  filterSection: { marginBottom: '24px', paddingBottom: '20px', borderBottom: '1px solid #3d332e' },
  filterSectionTitle: { fontFamily: "'JetBrains Mono', monospace", fontSize: '11px', fontWeight: 500, color: '#8f7666', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '12px' },
};
